import { describe, test, expect } from "bun:test";
import {
  generateApiKey,
  isValidApiKeyFormat,
  extractApiKey,
  hashApiKey,
  API_KEY_PREFIX,
  API_KEY_BYTE_LENGTH,
} from "./index.ts";

describe("generateApiKey", () => {
  test("returns a string starting with the makebook_ prefix", () => {
    expect(generateApiKey().startsWith("makebook_")).toBe(true);
  });

  test("returns a string of exactly 73 characters total", () => {
    expect(generateApiKey().length).toBe(73);
  });

  test("suffix after prefix contains only lowercase hex characters", () => {
    const key = generateApiKey();
    const suffix = key.slice(API_KEY_PREFIX.length);
    expect(suffix).toMatch(/^[a-f0-9]+$/);
  });

  test("successive calls produce different keys", () => {
    expect(generateApiKey()).not.toBe(generateApiKey());
  });
});

describe("isValidApiKeyFormat", () => {
  test("returns true for a key generated by generateApiKey", () => {
    expect(isValidApiKeyFormat(generateApiKey())).toBe(true);
  });

  test("returns false for empty string", () => {
    expect(isValidApiKeyFormat("")).toBe(false);
  });

  test("returns false for just the prefix with no suffix", () => {
    expect(isValidApiKeyFormat("makebook_")).toBe(false);
  });

  test("returns false for wrong prefix", () => {
    const suffix = "a".repeat(API_KEY_BYTE_LENGTH * 2);
    expect(isValidApiKeyFormat(`notmakebook_${suffix}`)).toBe(false);
  });

  test("returns false for correct prefix but suffix too short (63 chars)", () => {
    const suffix = "a".repeat(63);
    expect(isValidApiKeyFormat(`${API_KEY_PREFIX}${suffix}`)).toBe(false);
  });

  test("returns false for correct prefix but suffix too long (65 chars)", () => {
    const suffix = "a".repeat(65);
    expect(isValidApiKeyFormat(`${API_KEY_PREFIX}${suffix}`)).toBe(false);
  });

  test("returns false for correct prefix but uppercase hex in suffix", () => {
    const suffix = "A".repeat(API_KEY_BYTE_LENGTH * 2);
    expect(isValidApiKeyFormat(`${API_KEY_PREFIX}${suffix}`)).toBe(false);
  });

  test("returns false for correct prefix but non-hex characters in suffix", () => {
    const suffix = "x".repeat(API_KEY_BYTE_LENGTH * 2);
    expect(isValidApiKeyFormat(`${API_KEY_PREFIX}${suffix}`)).toBe(false);
  });
});

describe("extractApiKey", () => {
  test("returns null for undefined", () => {
    expect(extractApiKey(undefined)).toBeNull();
  });

  test("returns null for empty string", () => {
    expect(extractApiKey("")).toBeNull();
  });

  test("extracts key from Bearer format", () => {
    const key = generateApiKey();
    expect(extractApiKey(`Bearer ${key}`)).toBe(key);
  });

  test("extracts key from bare makebook_ format", () => {
    const key = generateApiKey();
    expect(extractApiKey(key)).toBe(key);
  });

  test("returns null for Bearer with invalid key", () => {
    expect(extractApiKey("Bearer invalid_key")).toBeNull();
  });

  test("returns null for Bearer with no key after it", () => {
    expect(extractApiKey("Bearer ")).toBeNull();
  });

  test("returns null for lowercase bearer prefix", () => {
    const key = generateApiKey();
    expect(extractApiKey(`bearer ${key}`)).toBeNull();
  });

  test("trims trailing whitespace from Bearer format", () => {
    const key = generateApiKey();
    expect(extractApiKey(`Bearer ${key}  `)).toBe(key);
  });
});

describe("hashApiKey", () => {
  test("returns a 64-character hex string", () => {
    expect(hashApiKey(generateApiKey())).toMatch(/^[a-f0-9]{64}$/);
  });

  test("returns the same hash for the same input", () => {
    const key = generateApiKey();
    expect(hashApiKey(key)).toBe(hashApiKey(key));
  });

  test("returns different hashes for different inputs", () => {
    expect(hashApiKey(generateApiKey())).not.toBe(hashApiKey(generateApiKey()));
  });

  test("handles empty string without throwing", () => {
    expect(() => hashApiKey("")).not.toThrow();
    expect(hashApiKey("").length).toBe(64);
  });
});
